### ISSUE TITLE
Code model structures ID using Enum

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastastore#131]
Would be nice to have unique id's for model structures. This would allow for easily creation of time series models via the id and identification of the structure given an id.

Somethign like: 

```python
from enum import IntEnum

class Rfunc(IntEnum):
    Exponential = 0
    Gamma = 1
    Hantush = 2

class Recharge(IntEnum):
    Linear = 0
    FlexModel = 1

class Wells(Flag):
    No = 0
    Schoonhoven = 1
    Bergambacht = 2

def make_model(code):
    pass

code = f"{Rfunc.Exponential}{Recharge.Linear}{Wells.Schoonhoven}" # 101

```

**Comment by dbrakenhoff** [comment]
I think it will be difficult to implement something sufficiently generic that works in all/most cases?

- What if you have Recharge, River and Wells?
- How do you indicate multiple wells in a WellModel?
- If you want to indicate both rfunc/stress, you need two numbers for each stress, which already makes it much harder to interpret the code?

My feeling is this is best developed in a specific project. Let me know what you think!

**Comment by martinvonk** [comment]
I agree that it is difficult and probably annoying to build. I thought maybe each stress and oseries could get a unique Enum ID from which the model can be built. But I think this would be too cumbersome.

**Comment by martinvonk** [comment]
https://www.youtube.com/watch?v=TAMbq0iRUsA
