### ISSUE TITLE
JSON can't handle int in metadata

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastastore#136]
I often get this error when adding metadata to pastastore: TypeError: Object of type int64 is not JSON serializable
This happens because there is an int in the metadata but this is not really clear from the error. So would be nice to check the metadata before parsing and give a more informative error.

**Comment by dbrakenhoff** [comment]
Its probably worth updating the PastasEncoder class to also check for numpy.integer and converting to int. I will open an issue there:

 https://github.com/pastas/pastas/issues/822

**Comment by dbrakenhoff** [comment]
Fixed in pastas: https://github.com/pastas/pastas/pull/823
