### ISSUE TITLE
Arctic + Pandas issues

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastastore#33]
Arctic is (somewhat) working on sorting out their pandas version issues (e.g. see https://github.com/man-group/arctic/issues/903#issue-859998025).

As a result of this work, pastastore tests are failing when using the pandas 1.0.3 version that arctic says it requires, but they pass when using version 1.1.5. As a temporary fix the installation of pandas 1.1.5 in pastastore tests/ci is hardcoded. Note this does lead to a dependency conflict notification. 

Current advice for pastastore users who also use the `ArcticConnector` is to use pandas 1.1.5.

Developments on this issue will be posted here.

**Comment by rubencalje** [comment]
Can we remove the pandas 1.1.5 dependency? This causes a lot of problems in my conda installation... Maybe we can check the pandas version when using the ArcticConnector?

**Comment by dbrakenhoff** [comment]
Sure :)

**Comment by dbrakenhoff** [comment]
Tests passing locally for PasConnector, DictConnector and PystoreConnector with pandas 1.3.3. So seems to be working fine. Ill commit the change now.

**Comment by rubencalje** [comment]
Great!

**Comment by dbrakenhoff** [comment]
Closing issue, see #79
