### ISSUE TITLE
Error writing pastastore to .zip file

### ISSUE THREAD

**Issue by OnnoEbbens** [pastas/pastastore#35]
When I run the code in this [notebook](https://github.com/MAMBA-python/course-material/blob/dev/Exercise_notebooks/On_topic/19_pastas/4_pastastore.ipynb)

I get the following error:
`ValueError: DataFrame index must be unique for orient='columns'.`

when trying to write the pastastore to a .zip file using:
`store.to_zip('pastasstore.zip', overwrite=True)`

**Comment by dbrakenhoff** [comment]
Duplicate timestamps by any chance?

**Comment by dbrakenhoff** [comment]
It's because of NaT timestamps in the timeseries
