### ISSUE TITLE
make Connector methods directly available in PastaStore

### ISSUE THREAD

**Issue by dbrakenhoff** [pastas/pastastore#7]
Suggestion to make the read/write/delete methods directly available under the PastaStore object.

So the following code
```python
ml = pstore.conn.get_models("my_little_model")
```
would become:
```python
ml = pstore.get_models("my_little_model")
```

This can be done by registering all the (non_internal) methods from the Connector when initializing a PastaStore object, e.g:

```python
def __init__(self, ..., conn):
    ...
    self.get_models = conn.get_models
```
I kind of liked having a split between the read/write/delete methods and the other logic, but I think typing laziness will win the day, so I will add this in a next release.

**Comment by rubencalje** [comment]
+1

**Comment by OnnoEbbens** [comment]
+1

**Comment by dbrakenhoff** [comment]
Added in 07803cdfab94909c3e73782da7371866993bae84.
