### ISSUE TITLE
Plot both oseries and stresses by default in data_availability plot

### ISSUE THREAD

**Issue by martinvonk** [pastas/pastastore#90]
Currently the data_availability plots needs a library name (`libname` argument): `"oseries"` v `"stresses"`
https://github.com/pastas/pastastore/blob/28ea9f2b7eea502cfb9006cb839b0ad01eef4bc7/pastastore/plotting.py#L210-L226

I'd like to make the default None which plots both libraries in a plot like the one below. Here the oseries are plotted in the upper Axes, and stresses in the lower Axes and the colorbar is shared. 
![01_Data_Availability](https://user-images.githubusercontent.com/66305055/226660302-02c8ffad-fe6d-438c-a3d3-77974bd9178a.png)

Thoughts @dbrakenhoff ?

**Comment by dbrakenhoff** [comment]
I'd add a method `data_availability_all()` and implement this option there.

**Comment by martinvonk** [comment]
Let's just leave it at is. I can just copy the code stated here, no need for an extra plot method.
